// discover_formulas.ts — Populate formula registry for all supported pool types
//
// Assigns formula IDs to pools based on pool type. EVM failures get -1.
// After writing, rebuild the harness and run correctness to find mismatches.
//
// Usage:
//   node evm-quoter/scripts/discover_formulas.ts [--write]

import { readFileSync, writeFileSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { createQuoter, loadPools, buildStateOverrides } from "../sdk.ts";

const __dirname = dirname(fileURLToPath(import.meta.url));
const REGISTRY_PATH = join(__dirname, "../go/formulas/registry.txt");
const STATE_SERVER = "ws://127.0.0.1:7449";

const doWrite = process.argv.includes("--write");

// Pool type → formula ID mapping
const FORMULA_MAP: Record<number, number> = {
  2: 0,   // LFJ V1 → V2 constant product
  8: 0,   // V2 family → V2 constant product
  7: 1,   // Pharaoh V1
  0: 2,   // Uniswap V3 / Pharaoh V3
  3: 3,   // LFJ V2 Liquidity Book
  1: 4,   // Algebra V1 Integral
  4: 5,   // DODO PMM
};

const FORMULA_NAMES: Record<number, string> = {
  0: "V2 constant product 30bps",
  1: "Pharaoh V1",
  2: "V3 tick-walking",
  3: "LFJ V2 Liquidity Book",
  4: "Algebra V1 Integral",
  5: "DODO PMM",
  [-1]: "invalid (FoT/broken)",
};

async function main() {
  const allPools = loadPools(null, 5000);
  const eligible = allPools.filter(p => FORMULA_MAP[p.poolType] !== undefined);
  console.log(`Loaded ${allPools.length} total, ${eligible.length} formula-eligible`);

  const { overrides } = buildStateOverrides(eligible);

  // Quote all via EVM
  console.log("Quoting via EVM...");
  const quoter = await createQuoter("native", { stateServerUrl: STATE_SERVER });
  await quoter.quotePoolBatch(eligible, overrides); // warm
  const results = await quoter.quotePoolBatch(eligible, overrides);
  quoter.close();

  // Build registry
  const byFormula: Record<number, { ok: number; fail: number }> = {};
  const registry: string[] = [
    "# Formula registry — auto-generated by discover_formulas",
    "# format: pool_address:formula_id",
    "# 0=V2, 1=PharaohV1, 2=V3, -1=invalid",
  ];

  for (let i = 0; i < eligible.length; i++) {
    const p = eligible[i];
    const r = results[i];
    const formulaId = FORMULA_MAP[p.poolType];

    if (!r.ok || BigInt(r.returnData) === 0n) {
      registry.push(`${p.pool.toLowerCase()}:-1`);
      if (!byFormula[-1]) byFormula[-1] = { ok: 0, fail: 0 };
      byFormula[-1].fail++;
    } else {
      registry.push(`${p.pool.toLowerCase()}:${formulaId}`);
      if (!byFormula[formulaId]) byFormula[formulaId] = { ok: 0, fail: 0 };
      byFormula[formulaId].ok++;
    }
  }

  console.log("\nResults:");
  for (const [id, stats] of Object.entries(byFormula).sort((a, b) => Number(a[0]) - Number(b[0]))) {
    const name = FORMULA_NAMES[Number(id)] || `formula ${id}`;
    console.log(`  ${name}: ${stats.ok} validated, ${stats.fail} failed`);
  }

  if (doWrite) {
    writeFileSync(REGISTRY_PATH, registry.join("\n") + "\n");
    console.log(`\nWrote ${REGISTRY_PATH} (${registry.length - 3} entries)`);
    console.log("Rebuild: cd evm-quoter && make build-native");
    console.log("Verify:  node bench.mjs 'evm/correctness' --dry-run");
  } else {
    console.log("\nDry run — pass --write to save");
  }

  process.exit(0);
}

main().catch(err => { console.error(err); process.exit(1); });
